
export interface ArtConfig {
  subject: string;
  feature: string;
  color: string;
  count: string;
  backgroundTexture: string;
}

export interface ArtPiece {
  id: string;
  url: string;
  config: ArtConfig;
  prompt: string;
  timestamp: number;
}

export enum GeneratorState {
  IDLE = 'IDLE',
  GENERATING = 'GENERATING',
  ERROR = 'ERROR',
}

export type ViewMode = 'single' | 'infinite' | 'favorites';

export const NEON_COLORS = [
  "neon yellow",
  "neon cyan",
  "electric magenta",
  "bright lime green",
  "vibrant orange",
  "electric blue",
  "hot pink",
  "glowing violet",
  "cyan",
  "magenta"
];

export interface SubjectTheme {
  name: string;
  feature: string;
}

export const SUBJECTS: SubjectTheme[] = [
  { name: "flying eagles", feature: "wing spans and beak tips" },
{ name: "running horses", feature: "mane flows and hoof details" },
{ name: "swimming dolphins", feature: "dorsal fins and tail flukes" },
{ name: "posing lions", feature: "mane edges and ear tufts" },
{ name: "climbing monkeys", feature: "tail curls and paw grips" },
{ name: "elephant herds", feature: "trunk tips and tusk curves" },
{ name: "flamingo flocks", feature: "long necks and knee bends" },
{ name: "penguin waddles", feature: "flippers and beak points" },
{ name: "fox silhouettes", feature: "bushy tails and pointed ears" },
{ name: "bear stands", feature: "claw outlines and snout shapes" },
{ name: "whale breaches", feature: "blowhole sprays and fin edges" },
{ name: "shark patrols", feature: "dorsal fins and gill slits" },
{ name: "bat swarms", feature: "wing membranes and ear flares" },
{ name: "peacock fans", feature: "tail feathers and crest tops" },
{ name: "rhino charges", feature: "horn tips and ear folds" },
{ name: "giraffe necks", feature: "ossicone knobs and tail tufts" },
{ name: "zebra stripes", feature: "mane ridges and hoof lines" },
{ name: "crocodile lurks", feature: "jaw ridges and tail scales" },
{ name: "tiger prowls", feature: "ear backs and whisker spots" },
{ name: "panda sits", feature: "ear patches and thumb claws" },
{ name: "koala clings", feature: "ear rounds and nose shine" },
{ name: "camel caravans", feature: "humps and leg joints" },
{ name: "hippo yawns", feature: "tooth curves and ear flaps" },
{ name: "mountain goats", feature: "horn arcs and hoof cracks" },
{ name: "wolf packs", feature: "ear points and tail brushes" },
{ name: "seahorses curl", feature: "tail coils and dorsal fins" },
{ name: "octopus drifts", feature: "tentacle suckers and eye pupils" },
{ name: "crab scuttles", feature: "claw pincers and leg joints" },
{ name: "lobster poses", feature: "antennae and tail fans" },
{ name: "sea turtles", feature: "shell ridges and flipper edges" },
{ name: "elegant swans", feature: "neck curves and wing tips" },
{ name: "heron stalks", feature: "beak spears and leg struts" },
{ name: "frog leaps", feature: "toe pads and eye bulges" },
{ name: "snake coils", feature: "scale patterns and tongue flicks" },
{ name: "scorpion strikes", feature: "tail stingers and pincer claws" },
{ name: "ladybugs land", feature: "spot dots and antenna knobs" },
{ name: "dragonflies hover", feature: "wing veins and tail segments" },
{ name: "beetle crawls", feature: "elytra edges and leg spines" },
{ name: "moth flutters", feature: "wing scales and antenna feathers" },
{ name: "praying mantis", feature: "raptorial arms and eye stalks" },
{ name: "spider webs", feature: "leg joints and abdomen swells" },
{ name: "ant columns", feature: "antennae bends and mandible jaws" },
{ name: "palm trees sway", feature: "frond tips and trunk knots" },
{ name: "cactus stands", feature: "spine clusters and arm ribs" },
{ name: "bamboo groves", feature: "culm rings and leaf sheaths" },
{ name: "mushroom clusters", feature: "gill undersides and stem rings" },
{ name: "fern fronds", feature: "pinna edges and stipe bases" },
{ name: "ivy climbs", feature: "leaf veins and tendril curls" },
{ name: "rose bushes", feature: "thorn pricks and petal whorls" },
{ name: "sunflowers turn", feature: "petal rays and seed disks" },
{ name: "lotus blooms", feature: "petal overlaps and seed pods" },
{ name: "orchid spikes", feature: "lip lobes and column tips" },
{ name: "succulent rosettes", feature: "leaf tips and spine points" },
{ name: "ancient ruins", feature: "column flutes and arch keystones" },
{ name: "gothic spires", feature: "pinnacle tips and gargoyle snouts" },
{ name: "sailing ships", feature: "mast tops and sail booms" },
{ name: "hot air balloons", feature: "gondola baskets and burner flames" },
{ name: "rocket launches", feature: "fin roots and nozzle bells" },
{ name: "vintage cars", feature: "headlight rims and fender curves" },
{ name: "bicycle racers", feature: "spoke wheels and handle grips" },
{ name: "kayak paddles", feature: "blade edges and shaft grips" },
{ name: "windsurfers glide", feature: "fin keels and sail booms" },
{ name: "skateboard tricks", feature: "wheel trucks and deck kicks" },
{ name: "guitar strummers", feature: "fret markers and headstock tuners" },
{ name: "drum kits", feature: "cymbal stands and snare wires" },
{ name: "violin bows", feature: "bridge curves and string vibes" },
{ name: "yoga poses", feature: "hand mudras and foot arches" },
{ name: "ballet leaps", feature: "toe shoes and arm extensions" },
{ name: "karate kicks", feature: "gi belts and fist knuckles" },
{ name: "soccer goals", feature: "net meshes and post bends" },
{ name: "basketball dunks", feature: "rim nets and shoe treads" },
{ name: "abstract waves", feature: "crest foams and trough dips" },
{ name: "geometric stars", feature: "point tips and inner polygons" },
{ name: "curved bridges", feature: "cable stays and arch ribs" },
{ name: "lighthouse beams", feature: "lantern domes and rail caps" },
{ name: "wind turbines", feature: "blade twists and nacelle vents" },
{ name: "solar panels", feature: "frame edges and cell grids" },
{ name: "clock towers", feature: "hand tips and numeral serifs" },
{ name: "fountain sprays", feature: "jet arcs and basin rims" },
{ name: "lantern glows", feature: "glass panes and handle hooks" },
{ name: "book stacks", feature: "page edges and spine labels" },
{ name: "crown jewels", feature: "gem facets and prong settings" },
{ name: "sword sheaths", feature: "hilt guards and pommel caps" },
{ name: "shield emblems", feature: "boss centers and rim rivets" },
{ name: "winged helmets", feature: "plume crests and cheek guards" },
{ name: "crystal goblets", feature: "stem flares and foot rims" },
{ name: "porcelain teapots", feature: "spout lips and handle curves" },
{ name: "brass lamps", feature: "shade fringes and base knops" },
{ name: "feather plumes", feature: "vane barbs and quill shafts" },
{ name: "leaf veils", feature: "midrib veins and margin serrations" },
  { name: "front-facing cats", feature: "ears and collar tags" },
  { name: "perched birds", feature: "wing tips and eye rings" },
  { name: "slender trees", feature: "select leaves and thin branches" },
  { name: "standing human silhouettes", feature: "subtle cheekbones and wrist bracelets" },
  { name: "school of fish", feature: "fin edges and eye spots" },
  { name: "howling wolves", feature: "eyes and fur tips" },
  { name: "watching owls", feature: "large eyes and talons" },
  { name: "floating jellyfish", feature: "trailing tentacles and bells" },
  { name: "abstract statues", feature: "sharp geometric edges" },
  { name: "dancing figures", feature: "flowing dress hems and shoes" },
  { name: "grazing deer", feature: "antler tips and nose" },
  { name: "resting butterflies", feature: "wing patterns and antennae" },
  { name: "blooming flowers", feature: "petal edges and stamens" },
  { name: "modern vases", feature: "rims and curves" },
  { name: "minimalist chairs", feature: "legs and backrest edges" }
];

export const COUNTS = ["single large", "pair of", "group of 3", "cluster of 4", "collection of"];

export const BACKGROUND_TEXTURES = [
  "gentle haze veils",
"whispering smoke tendrils",
"faint charcoal strokes",
"velvety shadow gradients",
"pale ink bleeds",
"subdued linen textures",
"airy vapor trails",
"ghostly pencil wisps",
"muted ash dispersions",
"silken mist drifts",
"delicate charcoal dust",
"softened fog banks",
"ethereal vapor sheens",
"subtle canvas weaves",
"faintly luminous motes",
"whispy cloud filaments",
"pale watercolor veils",
"diffuse graphite halos",
"gentle steam curls",
"minimalist fiber grains",
"translucent dew films",
"airy pollen scatters",
"softened dusk blooms",
"delicate soot flecks",
"veiled dawn hazes",
"faintly etched sands",
"subdued vapor blooms",
"ethereal frost crystals",
"gentle plume dispersals",
"pale mist congeals",
"whisper thin glimmers",
"muted canvas breaths",
"silky fog lattices",
"diffuse ember glows",
"airy chalk residues",
"subtle haze fractals",
"faintly drifting spores",
"velvet twilight fades",
"ghostly ink vapors",
"delicate ash veils",
"soft luminous threads",
"pale graphite mists",
"ethereal dew scatters",
"gentle cloud wisps",
"subdued linen hazes",
"whispy steam sheens",
"muted frost tendrils",
"faint charcoal blooms",
"airy vapor grains",
"silken shadow wisps",
"delicate mist lattices",
"pale soot dispersions",
"diffuse haze curls",
"velvety ember veils",
"ghostly pollen drifts",
"subtle canvas glimmers",
"faintly luminous sands",
"whispering dew films",
"softened ash trails",
"ethereal graphite blooms",
"gentle fog filaments",
"pale vapor sheens",
"muted dusk hazes",
"airy chalk veils",
"silky mist scatters",
"delicate cloud residues",
"subdued steam wisps",
"faint linen motes",
"whispy charcoal hazes",
"velvet frost dispersals",
"ghostly haze lattices",
"diffuse soot glimmers",
"pale ember threads",
"ethereal ash blooms",
"gentle vapor curls",
"subtle graphite veils",
"faintly drifting mists",
"airy pollen sheens",
"soft luminous grains",
"muted canvas wisps",
"silken dew hazes",
"delicate fog blooms",
"whisper thin shadows",
"pale mist filaments",
"velvety chalk drifts",
"ghostly vapor trails",
"subdued ash veils",
"faint charcoal scatters",
"ethereal linen glows",
"gentle haze residues",
"pale soot mists",
"airy steam lattices",
"diffuse frost wisps",
"muted ember hazes",
"silky cloud glimmers",
"delicate graphite curls",
"whispy dew blooms",
"softened pollen veils",
"faintly luminous sands",
"subtle canvas drifts",
"velvet mist threads",
"ghostly haze sheens",
"pale vapor grains",
"ethereal ash wisps",
"gentle fog lattices",
"airy charcoal blooms",
"diffuse dew hazes",
"muted steam veils",
"silken frost scatters",
"delicate cloud mists",
"whispering soot glimmers",
  "wisps of fog",
  "subtle watercolor bleed",
  "fine dust particles suspended in light",
  "faint graphite smudges",
  "soft, diffused cloud shadows",
  "delicate washes of pale gray",
  "minimalist canvas grain",
  "ethereal mist layers"
];
