
import { ArtPiece } from '../types';

interface NotionConfig {
  apiKey: string;
  databaseId: string;
}

export const pushToNotion = async (artPiece: ArtPiece, config: NotionConfig): Promise<boolean> => {
  const { apiKey, databaseId } = config;

  if (!apiKey || !databaseId) {
    throw new Error("Missing Notion credentials");
  }

  // Note: Direct calls to Notion API from browser are typically blocked by CORS.
  // This code assumes a CORS proxy or an environment that allows such requests.
  // If using a proxy, replace 'https://api.notion.com/v1/pages' with your proxy URL.
  const url = 'https://api.notion.com/v1/pages';

  const body = {
    parent: {
      database_id: databaseId,
    },
    properties: {
      "Subject": {
        title: [
          {
            text: {
              content: artPiece.config.subject,
            },
          },
        ],
      },
      "Prompt": {
        rich_text: [
          {
            text: {
              content: artPiece.prompt,
            },
          },
        ],
      },
      "Color Theme": {
        select: {
          name: artPiece.config.color,
        },
      },
      "Feature": {
        rich_text: [
          {
            text: {
              content: artPiece.config.feature,
            },
          },
        ],
      },
      "Created At": {
        date: {
          start: new Date(artPiece.timestamp).toISOString(),
        },
      }
    },
    // We cannot upload Base64 images directly to Notion properties requiring URLs.
    // We add the Base64 data as a code block in the page content for archival purposes.
    children: [
      {
        object: "block",
        type: "paragraph",
        paragraph: {
          rich_text: [
            {
              type: "text",
              text: {
                content: "Generated by Aether & Neon",
              },
            },
          ],
        },
      },
      {
        object: "block",
        type: "code",
        code: {
          caption: [{ type: "text", text: { content: "Prompt" } }],
          rich_text: [{ type: "text", text: { content: artPiece.prompt } }],
          language: "plain text"
        }
      }
    ]
  };

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Notion-Version': '2022-06-28',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      console.error("Notion API Error:", errorData);
      throw new Error(`Notion API failed: ${response.status} ${response.statusText}`);
    }

    return true;
  } catch (error) {
    console.error("Failed to push to Notion:", error);
    throw error;
  }
};
